project_name: "Advanced Software Engineering Project"
project_description: "A multi-agent system with parallel sub-projects for comprehensive software development"

# Global configuration applicable to all sub-projects
global:
  model_providers:
  - name: "ollama"
    base_url: "http://localhost:11434"
  default_model_settings:
    temperature: 0.2
    stream: false

# Define sub-projects that can run in parallel
sub_projects:
- name: "frontend-development"
  description: "Development of frontend components and user interfaces"
  priority: 1 # Lower numbers run first if dependencies allow
  parallel: true # Can run in parallel with other sub-projects

  # Tasks specific to this sub-project
  tasks:
  - name: "frontend-requirements-analysis"
    description: "Analyze frontend requirements and prepare specifications"
    agent: "frontend-analyst"
    input_key: "frontend_requirements"
    output_key: "frontend_specs"
    depends_on: []

  - name: "frontend-architecture-design"
    description: "Design frontend architecture and component structure. Make sure to use the latest technologies and best practices. Create a detailed plan for the project and then split into smaller tasks. Go!"
    agent: "frontend-architect"
    input_key: "frontend_specs"
    output_key: "frontend_architecture"
    depends_on: [ "frontend-requirements-analysis" ]

  - name: "ui-design"
    description: "Create UI/UX design system and mockups"
    agent: "ui-designer"
    input_key: "frontend_architecture"
    output_key: "ui_design"
    depends_on: [ "frontend-architecture-design" ]

  - name: "component-development"
    description: "Develop reusable frontend components"
    agent: "frontend-developer"
    input_key: "ui_design"
    output_key: "frontend_components"
    depends_on: [ "ui-design" ]

  - name: "frontend-integration"
    description: "Integrate components into a complete frontend application"
    agent: "frontend-developer"
    input_key: "frontend_components"
    output_key: "integrated_frontend"
    depends_on: [ "component-development" ]

  - name: "frontend-testing"
    description: "Test frontend application for bugs and usability issues"
    agent: "frontend-qa"
    input_key: "integrated_frontend"
    output_key: "frontend_test_results"
    depends_on: [ "frontend-integration" ]

  - name: "frontend-documentation"
    description: "Create documentation for frontend components and usage"
    agent: "technical-writer"
    input_key: "frontend_test_results"
    output_key: "frontend_documentation"
    depends_on: [ "frontend-testing" ]

- name: "backend-development"
  description: "Development of backend services, APIs, and business logic"
  priority: 1
  parallel: true

  tasks:
  - name: "backend-requirements-analysis"
    description: "Analyze backend requirements and prepare specifications"
    agent: "backend-analyst"
    input_key: "backend_requirements"
    output_key: "backend_specs"
    depends_on: []

  - name: "data-modeling"
    description: "Design database schemas and data models"
    agent: "data-architect"
    input_key: "backend_specs"
    output_key: "data_models"
    depends_on: [ "backend-requirements-analysis" ]

  - name: "api-design"
    description: "Design API endpoints and contracts"
    agent: "backend-architect"
    input_key: "backend_specs"
    output_key: "api_design"
    depends_on: [ "backend-requirements-analysis" ]

  - name: "database-implementation"
    description: "Implement database schemas and migrations"
    agent: "database-engineer"
    input_key: "data_models"
    output_key: "database_implementation"
    depends_on: [ "data-modeling" ]

  - name: "api-implementation"
    description: "Implement API endpoints and services"
    agent: "backend-developer"
    input_key: "api_design"
    output_key: "api_implementation"
    depends_on: [ "api-design" ]

  - name: "business-logic-implementation"
    description: "Implement core business logic and services"
    agent: "backend-developer"
    input_key: "backend_specs"
    output_key: "business_logic"
    depends_on: [ "backend-requirements-analysis" ]

  - name: "backend-integration"
    description: "Integrate all backend components"
    agent: "backend-developer"
    input_key: "api_implementation"
    output_key: "integrated_backend"
    depends_on: [ "api-implementation", "business-logic-implementation", "database-implementation" ]

  - name: "backend-testing"
    description: "Test backend services and APIs"
    agent: "backend-qa"
    input_key: "integrated_backend"
    output_key: "backend_test_results"
    depends_on: [ "backend-integration" ]

  - name: "backend-documentation"
    description: "Create API documentation and developer guides"
    agent: "technical-writer"
    input_key: "backend_test_results"
    output_key: "backend_documentation"
    depends_on: [ "backend-testing" ]

- name: "infrastructure-setup"
  description: "Setup and configuration of infrastructure and deployment pipeline"
  priority: 1
  parallel: true

  tasks:
  - name: "infrastructure-requirements-analysis"
    description: "Analyze infrastructure requirements"
    agent: "infrastructure-analyst"
    input_key: "infrastructure_requirements"
    output_key: "infrastructure_specs"
    depends_on: []

  - name: "infrastructure-architecture-design"
    description: "Design cloud infrastructure architecture"
    agent: "infrastructure-architect"
    input_key: "infrastructure_specs"
    output_key: "infrastructure_architecture"
    depends_on: [ "infrastructure-requirements-analysis" ]

  - name: "infrastructure-implementation"
    description: "Implement infrastructure as code"
    agent: "devops-engineer"
    input_key: "infrastructure_architecture"
    output_key: "infrastructure_implementation"
    depends_on: [ "infrastructure-architecture-design" ]

  - name: "ci-cd-pipeline-setup"
    description: "Setup continuous integration and deployment pipelines"
    agent: "devops-engineer"
    input_key: "infrastructure_architecture"
    output_key: "ci_cd_pipeline"
    depends_on: [ "infrastructure-architecture-design" ]

  - name: "monitoring-setup"
    description: "Setup monitoring and alerting systems"
    agent: "devops-engineer"
    input_key: "infrastructure_architecture"
    output_key: "monitoring_system"
    depends_on: [ "infrastructure-implementation" ]

  - name: "security-implementation"
    description: "Implement security controls and policies"
    agent: "security-engineer"
    input_key: "infrastructure_implementation"
    output_key: "security_implementation"
    depends_on: [ "infrastructure-implementation" ]

  - name: "infrastructure-testing"
    description: "Test infrastructure deployment and reliability"
    agent: "infrastructure-qa"
    input_key: "infrastructure_implementation"
    output_key: "infrastructure_test_results"
    depends_on: [ "infrastructure-implementation", "security-implementation", "ci-cd-pipeline-setup", "monitoring-setup" ]

  - name: "infrastructure-documentation"
    description: "Create infrastructure documentation and runbooks"
    agent: "technical-writer"
    input_key: "infrastructure_test_results"
    output_key: "infrastructure_documentation"
    depends_on: [ "infrastructure-testing" ]

- name: "integration-and-deployment"
  description: "Integration of all sub-projects and final deployment"
  priority: 2 # Higher number means this runs after other sub-projects
  parallel: false # Cannot run in parallel since it depends on all other sub-projects

  tasks:
  - name: "cross-project-integration"
    description: "Integrate frontend, backend, and infrastructure components"
    agent: "integration-engineer"
    input_key: [ "integrated_frontend", "integrated_backend", "infrastructure_implementation" ]
    output_key: "integrated_system"
    depends_on: [] # Dependencies are managed at the sub-project level

  - name: "system-testing"
    description: "Perform end-to-end system testing"
    agent: "qa-lead"
    input_key: "integrated_system"
    output_key: "system_test_results"
    depends_on: [ "cross-project-integration" ]

  - name: "performance-testing"
    description: "Test system performance and scalability"
    agent: "performance-engineer"
    input_key: "integrated_system"
    output_key: "performance_test_results"
    depends_on: [ "cross-project-integration" ]

  - name: "security-testing"
    description: "Perform security testing and vulnerability assessment"
    agent: "security-engineer"
    input_key: "integrated_system"
    output_key: "security_test_results"
    depends_on: [ "cross-project-integration" ]

  - name: "bug-fixing"
    description: "Fix bugs and issues identified during testing"
    agent: "lead-developer"
    input_key: [ "system_test_results", "performance_test_results", "security_test_results" ]
    output_key: "fixed_system"
    depends_on: [ "system-testing", "performance-testing", "security-testing" ]

  - name: "deployment"
    description: "Deploy the final system to production"
    agent: "devops-engineer"
    input_key: "fixed_system"
    output_key: "deployed_system"
    depends_on: [ "bug-fixing" ]

  - name: "final-documentation"
    description: "Compile all documentation into a comprehensive package"
    agent: "documentation-lead"
    input_key: [ "frontend_documentation", "backend_documentation", "infrastructure_documentation", "deployed_system" ]
    output_key: "final_documentation"
    depends_on: [ "deployment" ]

  - name: "project-review"
    description: "Conduct final project review and retrospective"
    agent: "project-reviewer"
    input_key: [ "final_documentation", "deployed_system" ]
    output_key: "project_review"
    depends_on: [ "final-documentation" ]

# Define agents used in the project
agents:
- name: "frontend-analyst"
  type: "analyst"
  role: "Frontend Requirements Analyst"
  description: "Analyzes frontend requirements and prepares detailed specifications"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a frontend requirements analyst responsible for analyzing project requirements and preparing detailed specifications for the frontend development team. Focus on user experience, interactivity, and client-side needs."

- name: "frontend-architect"
  type: "architect"
  role: "Frontend Architect"
  description: "Designs frontend architecture and component structure"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes for this complex model
  system_prompt: "You are a frontend architect responsible for designing scalable and maintainable frontend architectures. Create clear component hierarchies, state management strategies, and UI architecture patterns."

- name: "ui-designer"
  type: "designer"
  role: "UI/UX Designer"
  description: "Creates UI/UX design systems and visual components"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a UI/UX designer who creates beautiful, intuitive, and accessible user interfaces. Follow modern design principles, ensure consistency, and prioritize user experience."

- name: "frontend-developer"
  type: "developer"
  role: "Frontend Developer"
  description: "Implements frontend components and interfaces"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a frontend developer who implements responsive, accessible, and performant user interfaces. Write clean, maintainable code following best practices and modern frontend frameworks."

- name: "frontend-qa"
  type: "qa_engineer"
  role: "Frontend QA Engineer"
  description: "Tests frontend applications for bugs and usability issues"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a frontend QA engineer who thoroughly tests web applications. Focus on cross-browser compatibility, responsiveness, accessibility, and overall user experience."

- name: "backend-analyst"
  type: "analyst"
  role: "Backend Requirements Analyst"
  description: "Analyzes backend requirements and prepares detailed specifications"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a backend requirements analyst responsible for analyzing project requirements and preparing detailed specifications for the backend development team. Focus on data flow, business logic, and system architecture."

- name: "data-architect"
  type: "architect"
  role: "Data Architect"
  description: "Designs database schemas and data models"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a data architect who designs efficient and scalable database schemas. Create normalized data models that balance performance and maintainability."

- name: "backend-architect"
  type: "architect"
  role: "Backend Architect"
  description: "Designs API endpoints and services architecture"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a backend architect who designs scalable and maintainable API architectures. Create clear service boundaries, efficient data flows, and follow REST or GraphQL best practices."

- name: "database-engineer"
  type: "developer"
  role: "Database Engineer"
  description: "Implements database schemas and migrations"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
    max_retries: 3 # Retry 3 times
    retry_delay: 10 # Wait 10 seconds between retries
  system_prompt: "You are a database engineer who implements efficient database schemas and migrations. Write optimized queries and ensure data integrity and performance."

- name: "backend-developer"
  type: "developer"
  role: "Backend Developer"
  description: "Implements API endpoints and business logic"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a backend developer who implements secure, scalable, and efficient API endpoints and business logic. Write clean, testable code following best practices."

- name: "backend-qa"
  type: "qa_engineer"
  role: "Backend QA Engineer"
  description: "Tests backend services and APIs"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a backend QA engineer who thoroughly tests APIs and backend services. Focus on functional correctness, edge cases, performance, and security."

- name: "infrastructure-analyst"
  type: "analyst"
  role: "Infrastructure Requirements Analyst"
  description: "Analyzes infrastructure requirements"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are an infrastructure requirements analyst responsible for analyzing project requirements and preparing detailed specifications for the infrastructure team. Focus on scalability, reliability, and operational needs."

- name: "infrastructure-architect"
  type: "architect"
  role: "Infrastructure Architect"
  description: "Designs cloud infrastructure architecture"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are an infrastructure architect who designs scalable, secure, and cost-effective cloud infrastructure. Create architectures that balance performance, reliability, and operational efficiency."

- name: "devops-engineer"
  type: "developer"
  role: "DevOps Engineer"
  description: "Implements infrastructure as code and CI/CD pipelines"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a DevOps engineer who implements infrastructure as code and automated CI/CD pipelines. Create reliable, repeatable deployment processes and infrastructure configurations."

- name: "security-engineer"
  type: "engineer"
  role: "Security Engineer"
  description: "Implements security controls and conducts security testing"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a security engineer who implements robust security controls and conducts thorough security testing. Identify and remediate vulnerabilities and ensure compliance with security best practices."

- name: "infrastructure-qa"
  type: "qa_engineer"
  role: "Infrastructure QA Engineer"
  description: "Tests infrastructure deployment and reliability"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are an infrastructure QA engineer who tests deployment processes and infrastructure reliability. Focus on automation, scalability, and resilience to failures."

- name: "technical-writer"
  type: "writer"
  role: "Technical Writer"
  description: "Creates clear and comprehensive technical documentation"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a technical writer who creates clear, comprehensive, and well-structured documentation. Make complex technical concepts accessible to both technical and non-technical audiences."

- name: "integration-engineer"
  type: "engineer"
  role: "Integration Engineer"
  description: "Integrates components from different teams and sub-projects"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are an integration engineer who ensures different components work together seamlessly. Identify and resolve integration issues and ensure end-to-end functionality."

- name: "qa-lead"
  type: "qa_engineer"
  role: "QA Lead"
  description: "Leads system testing and quality assurance efforts"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a QA lead who oversees system testing and ensures overall quality. Design comprehensive test plans and coordinate testing across different components and teams."

- name: "performance-engineer"
  type: "engineer"
  role: "Performance Engineer"
  description: "Tests system performance and scalability"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a performance engineer who tests system performance, scalability, and efficiency. Identify bottlenecks and provide recommendations for optimization."

- name: "lead-developer"
  type: "developer"
  role: "Lead Developer"
  description: "Coordinates development efforts and resolves complex issues"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a lead developer who coordinates development efforts and resolves complex technical issues. Ensure code quality, mentor other developers, and make critical technical decisions."

- name: "documentation-lead"
  type: "writer"
  role: "Documentation Lead"
  description: "Coordinates documentation efforts across the project"
  model_name: "qwen3:latest"
  model_provider: "ollama"
  system_prompt: "You are a documentation lead who coordinates documentation efforts across different teams and ensures consistent, comprehensive documentation. Organize information logically and ensure it meets the needs of all stakeholders."

- name: "project-reviewer"
  type: "reviewer"
  role: "Project Reviewer"
  description: "Conducts final project review and retrospective"
  model_name: "deepseek-r1:latest"
  model_provider: "ollama"
  model_settings:
    timeout: 1800 # Increase timeout to 10 minutes
  system_prompt: "You are a project reviewer who evaluates the completed project against requirements and best practices. Provide constructive feedback for future improvements and identify strengths and weaknesses."
